
package xx.mx.uv.consumo.wsdl;

import java.math.BigDecimal;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "iPresupuesto", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPresupuesto {


    /**
     * 
     * @param id
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/mostrarPresupuestoDisponible")
    @WebResult(name = "mostrarPresupuestoDisponibleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mostrarPresupuestoDisponible", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.MostrarPresupuestoDisponible")
    @ResponseWrapper(localName = "mostrarPresupuestoDisponibleResponse", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.MostrarPresupuestoDisponibleResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/mostrarPresupuestoDisponible", output = "http://tempuri.org/iPresupuesto/mostrarPresupuestoDisponibleResponse")
    public BigDecimal mostrarPresupuestoDisponible(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     * 
     * @param monto
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/agregarPresupuesto")
    @WebResult(name = "agregarPresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "agregarPresupuesto", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.AgregarPresupuesto")
    @ResponseWrapper(localName = "agregarPresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.AgregarPresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/agregarPresupuesto", output = "http://tempuri.org/iPresupuesto/agregarPresupuestoResponse")
    public String agregarPresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "monto", targetNamespace = "http://tempuri.org/")
        BigDecimal monto);

    /**
     * 
     * @param monto
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/sustraerPresupuesto")
    @WebResult(name = "sustraerPresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sustraerPresupuesto", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.SustraerPresupuesto")
    @ResponseWrapper(localName = "sustraerPresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.SustraerPresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/sustraerPresupuesto", output = "http://tempuri.org/iPresupuesto/sustraerPresupuestoResponse")
    public String sustraerPresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "monto", targetNamespace = "http://tempuri.org/")
        BigDecimal monto);

    /**
     * 
     * @param monto
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/alcanzaElPresupuesto")
    @WebResult(name = "alcanzaElPresupuestoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "alcanzaElPresupuesto", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.AlcanzaElPresupuesto")
    @ResponseWrapper(localName = "alcanzaElPresupuestoResponse", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.AlcanzaElPresupuestoResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/alcanzaElPresupuesto", output = "http://tempuri.org/iPresupuesto/alcanzaElPresupuestoResponse")
    public boolean alcanzaElPresupuesto(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id,
        @WebParam(name = "monto", targetNamespace = "http://tempuri.org/")
        BigDecimal monto);

    /**
     * 
     * @return
     *     returns xx.mx.uv.consumo.wsdl.ArrayOfDepartamento
     */
    @WebMethod(action = "http://tempuri.org/iPresupuesto/mostrarDepartamentos")
    @WebResult(name = "mostrarDepartamentosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mostrarDepartamentos", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.MostrarDepartamentos")
    @ResponseWrapper(localName = "mostrarDepartamentosResponse", targetNamespace = "http://tempuri.org/", className = "xx.mx.uv.consumo.wsdl.MostrarDepartamentosResponse")
    @Action(input = "http://tempuri.org/iPresupuesto/mostrarDepartamentos", output = "http://tempuri.org/iPresupuesto/mostrarDepartamentosResponse")
    public ArrayOfDepartamento mostrarDepartamentos();

}
